import os

# unix, linux, mac  : 'clear'
# microsoft windows : 'CLS'
os.system('clear' if os.name is 'posix' else 'CLS')

BASEPATH = Dir('.').abspath

print '-----------------------------------------------------------------'
print '[YGG]  build ygg codebase library and run test,'
print '       on %s.' % BASEPATH
print '-----------------------------------------------------------------'



# build codebase library
print '    ======== build codebase library'

CPPPATH = [
    '../ext/include',
    '../',
  ]

env = Environment(CPPPATH=CPPPATH, CXXFLAGS=['-std=c++11', '-g', '-rdynamic'])



sources = [
    'object.cpp',
  ]

lib = env.StaticLibrary(target = 'codebase', source=sources)
env.Install('../lib', lib)
env.Alias('install', '../lib')



# build and run unittest
print '    ======== build codebase unittest'

# codebase
sources = [
    '../ext/src/gmock_main.cc',
    'object_test.cpp',
  ]

LIBS = [
    'gtest', 
    'codebase',
  ]

LIBPATH = [
    '../ext/lib',
    '../lib',
  ]

if os.name == 'posix':
  env.Append(LINKFLAGS=['-pthread'])
test = env.Program(target='test', source=sources, LIBS=LIBS, LIBPATH=LIBPATH)



# run after build complete
print '    ======== run codebase unittest'

Command(
  'unittest', 
  test, 
  lambda env, target, source: os.system(source[0].abspath))

