import os
import sys

# unix, linux, mac  : 'clear'
# microsoft windows : 'CLS'
os.system('clear' if os.name is 'posix' else 'CLS')

BASEPATH = Dir('.').abspath
ROOTPATH = os.path.join(BASEPATH, '..')
ROOTPATH = os.path.abspath(ROOTPATH)
#TESTPATH = os.path.join(BASEPATH, '../test')
#TESTPATH = os.path.abspath(TESTPATH)

sys.path.append(os.path.join(ROOTPATH, 'build/scons'))
import utils

print '-----------------------------------------------------------------'
print '[YGG]  build ygg codebase library and run test,'
print '       on %s.' % BASEPATH
print '-----------------------------------------------------------------'



# build codebase library
print '    ======== build codebase library'

CPPPATH = [
    '../ext/include',
    '../',
  ]

sources = [
    'object.cpp',
  ]

env = Environment(CPPPATH=CPPPATH, CXXFLAGS=['-std=c++11', '-g', '-rdynamic'])
env.StaticLibrary(target = 'codebase', source=sources)



# build and run unittest
print '    ======== build codebase unittest'

# codebase
sources = [
    'object_test.cpp',
    '../ext/src/gmock_main.cc',
  ]

LIBS = [
    'gtest', 
    'codebase',
  ]

LIBPATH = [
    '../ext/lib',
    './',
  ]

if os.name == 'posix':
  env.Append(LINKFLAGS=['-pthread'])
test = env.Program(target='test', source=sources, LIBS=LIBS, LIBPATH=LIBPATH)



# run after build complete
print '    ======== run codebase unittest'

Command(
  'unittest', 
  test, 
  lambda env, target, source: os.system(source[0].abspath))

