import os
import sys

# unix, linux, mac  : 'clear'
# microsoft windows : 'CLS'
os.system('clear' if os.name is 'posix' else 'CLS')

BASEPATH = Dir('.').abspath

print '-----------------------------------------------------------------'
print '[YGG]  build ygg net library and run test,'
print '       on %s.' % BASEPATH
print '-----------------------------------------------------------------'



# build net library
print '    ======== build net library'

CPPPATH = [
    '../ext/include',
    '../',
  ]

sources = [
    'http_server.cpp',
    'http_server_websocket_connection.cpp',
  ]

env = Environment(CPPPATH=CPPPATH, CXXFLAGS=['-std=c++11', '-g'])
lib = env.StaticLibrary(target='net', source=sources)
env.Install('../lib', lib)
env.Alias('install', '../lib')



# build and run unittest
print '    ======== build core unittest'

sources = [
    '../ext/src/gmock_main.cc',
    '../test/fake.cpp',
    '../test/vars.cpp',
    'http_server_test.cpp',
    'http_server_websocket_connection_test.cpp',
  ]

LIBS = [
    'libboost_chrono-mt-s',
    'libboost_system-mt-s',
    'libboost_thread-mt-s',
    'jsoncpp',
    'mongoose',
    'gtest', 
    'core',
    'net',
  ]

LIBPATH = [
    '../ext/lib',
    '../lib',
  ]

if os.name == 'posix':
  env.Append(LINKFLAGS=['-pthread'])
test = env.Program(target='test', source=sources, LIBS=LIBS, LIBPATH=LIBPATH)



# run after build complete
print '    ======== run server unittest'

Command(
  'unittest', 
  test, 
  lambda env, target, source: os.system(source[0].abspath))

